### ISSUE TITLE
Image height is not adjusted when overwriting existing image

### ISSUE THREAD

**Issue by Xenira** [pmsipilot/docker-compose-viz#35] opened 2018-03-06 14:22 UTC
Expected behavior: When using the force flag a new image (with new dimensions) is created and overwrites the current image.
Current behavior: The new image is written, but the dimensions are staying the same, causing information to be lost / out of bounds.

Steps to reproduce:

1. Create image using docker-compose.yml
1. Edit the docker-compose.yml
1. Recreate the image using the force option

**Comment by jubianchi** [comment] 2020-08-19 17:54
I can't reproduce this bug:

> 1. Create image using docker-compose.yml

![docker-compose](https://user-images.githubusercontent.com/327237/90671960-b4b3c800-e255-11ea-8366-5e3a94b313c9.png)

> 2. Edit the docker-compose.yml

> 3. Recreate the image using the force option

![docker-compose](https://user-images.githubusercontent.com/327237/90672033-cac18880-e255-11ea-9e53-43e0ff614869.png)


I'm closing it since no one else seems to have experienced this behavior.

**Closed by jubianchi** 2020-08-19 17:54 UTC
Labels: bug
